### ISSUE TITLE
[Bug] Can not begin to use issue

### ISSUE THREAD

**Issue by Kristinita** [Starli0n/SublimeVerbose#1]
### Summary

Verbose not work for me.

### Expected behavior

Correct run commands of Verbose.

### Actual behavior

I can not run Verbose commands.

![Verbose commands](http://i.imgur.com/5COQCL6.png)

### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I install Verbose via Package Control → I restart Sublime Text → `View` → if I click `Log Verbose`, `Log Commands` or `Log Input` nothing occurs.

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by Kristinita** [comment]
@Starli0n, may you add real examples of usage Verbose?

I understand, what is “Log Commands” and “Log Input”. Example — if I press <kbd>Ctrl+C</kbd>, I see in Sublime Text console:

```
key evt: control+c
command: copy_edit
```

But what is “Log Verbose”? May you add examples, where it works?

Thanks.

**Comment by Starli0n** [comment]
You can find a good example of `Log Verbose` inside the package [Open-Include](https://github.com/titoBouzout/Open-Include)
